### PR TITLE
Update User Guide to match intended List feature

### LINKED ISSUE #70: Update User Guide to match intended List feature

### PR DESCRIPTION
**Pull request by Rachael-Chan**
closes #70

### CODE REVIEW

**Review by AbdulrahmanAlRammah — CHANGES_REQUESTED** [review]
The other commands like help haven't been edited yet. It is better to specify that help is the only one that won't accept extraneous params.

**Comment by Rachael-Chan** [comment]
@AbdulrahmanAlRammah Changed accordingly.

**Review by Andrew22Teoh — APPROVED** [review]
LGTM!

**Review by AbdulrahmanAlRammah — APPROVED** [review]
LGTM!

**Pull request merged**
